### PR TITLE
Task balance saves all coins from bank task

### LINKED ISSUE #151: [BUG] Task balance handler breaks
See: https://github.com/CronCats/cw-croncat/blob/main/contracts/cw-croncat/src/manager.rs#L470

This needs logic to handle native tokens, cw20s, and when there are no tokens (empty vec).
Currently hardcoded 0 index causes proxycall to fail, which breaks rescheduling.

### PR DESCRIPTION
**Pull request by NinoLipartiia**
Close #151

### CODE REVIEW

**Review by mikedotexe — APPROVED** [review]

File: packages/cw-croncat-core/src/types.rs [hunk 1]
```diff
@@ -405,20 +405,22 @@ impl Task {
...
-        matches!(&self.interval, Interval::Cron(_) | Interval::Block(_))
+        matches!(
+            &self.interval,
+            Interval::Cron(_) | Interval::Block(_) | Interval::Immediate
+        )
     }
 
     pub fn contains_send_msg(&self) -> bool {
-        let result: bool = self.actions.iter().any(|a| -> bool {
+        self.actions.iter().any(|a| -> bool {
```
Comment (Buckram123) [inline packages/cw-croncat-core/src/types.rs:415]: Pretty sure it can infer type bool here

File: contracts/cw-croncat/src/manager.rs [hunk 2]
```diff
@@ -463,15 +463,20 @@ impl<'a> CwCroncat<'a> {
         ); //send completed event to balancer
            //If Send and reccuring task increment withdrawn funds so contract doesnt get drained
         let transferred_bank_tokens = msg.transferred_bank_tokens();
-        let task_to_finilize = task;
-        if task_to_finilize.contains_send_msg()
-            && task_to_finilize.is_recurring()
+        let mut task_to_finalize = task.clone();
```
Comment (Buckram123) [inline contracts/cw-croncat/src/manager.rs:466]: Isn't clone redundant here?

**Review by Buckram123 — COMMENTED** [review]
Interesting changes
