### PR TITLE
[FIX] Tasks with no actions can be created

### LINKED ISSUE #222: [BUG] Tasks with no actions can be created
Thought this was covered, but seems weird to allow empty actions array. Unless you really really wanna donate in a spammy way to agents. 😹

### PR DESCRIPTION
**Pull request by deveusss**
closes #222

### CODE REVIEW

File: contracts/cw-croncat/src/tasks.rs [hunk 1]
```diff
@@ -254,7 +254,9 @@ impl<'a> CwCroncat<'a> {
                 val: "Interval invalid".to_string(),
             });
         }
-
+        if task.actions.is_empty() {
+            return Err(ContractError::CoreError(CoreError::InvalidAction {}));
+        }
```
Comment (Buckram123) [inline contracts/cw-croncat/src/tasks.rs:259]: What if we move it inside `is_valid_msg_calculate_usage()` task's method?

**Review by Buckram123 — CHANGES_REQUESTED** [review]
Let's add a little test, just to make sure it's covered

**Review by Buckram123 — APPROVED** [review]
Nice to have that covered
