### PR TITLE
[FIX] Gas calc updates

### LINKED ISSUE #218: [BUG] Gas calc needs updates
Based on discussions, we need to:
* [x] change gas fraction to use numerator, and denominator to be 100
* [x] Remove all instances of _JUNO in our constants
* [x] Add config: gas_price (starting in instantiate)
* [x] Add config: gas_query_fee (starting in instantiate)
* [x] update the calculations for agent reimbursement & task balance sub in the proxy_call

### LINKED ISSUE #219: [FIX] Remove get_state method
Cleanup contract to save those critical kbs!

### PR DESCRIPTION
**Pull request by Buckram123**
Closes #218
~~Last thing to update is gas-benchmark, but it's ready for review~~ Done.

### CODE REVIEW

File: justfile [hunk 1]
```diff
@@ -24,6 +24,7 @@ schema:
 gen:
 	#!/usr/bin/env bash
 	cd typescript
+	yarn --cwd ./typescript build
```
Comment (deveusss) [inline justfile:27]: awesome)

**Review by deveusss — APPROVED** [review]
LGTM!

File: contracts/cw-croncat/src/contract.rs [hunk 2]
```diff
@@ -16,12 +16,18 @@ const DEFAULT_NOMINATION_DURATION: u16 = 360;
...
+/// Gas needed for single non-wasm query
+pub const GAS_QUERY_FEE: u64 = 5_000;
+/// Gas needed for single wasm query
+pub const GAS_WASM_QUERY_FEE: u64 = 60_000;
 /// We can't store gas_price as floats inside cosmwasm
-/// so insted of something like 0.1 we use GasFraction{1/10}
-pub const GAS_DENOMINATOR_DEFAULT_JUNO: u64 = 9;
+/// so insted of having 0.04 we use GasFraction{4/100}
+/// and multiply numerator by `gas_adjustment` (1.5)
+pub const GAS_NUMERATOR_DEFAULT: u64 = 6;
```
Comment (mikedotexe) [inline contracts/cw-croncat/src/contract.rs:29]: 👍🏼

**Review by mikedotexe — APPROVED** [review]
