### PR TITLE
[FIX] Cron / boundary issues

### LINKED ISSUE #221: [BUG] Cron / boundary issues
In UI testing, came across a couple weird instances:
* cannot use boundary.Time, the matcher basically forces Cron interval. I was using "Once" with Time
* attempting the following gives an error "Task Ended", which really seems wrong. Works using block interval.

```
{
  "validate_interval": {
    "interval": {
      "Cron": "0 0 * * * *"
    }
  }
}

{
  "create_task": {
    "task": {
      "interval": {
        "Cron": "0 0 * * * *"
      },
      "boundary": {
        "Time": {
          "start": "1671346994047000",
          "end": "1671347101964000"
        }
      },
      "stop_on_fail": false,
      "actions": [
        {
          "msg": {
            "bank": {
              "send": {
                "to_address": "juno1blmwjkg7uu4awajw5aunctjdce...rdpy",
                "amount": [
                  {
                    "denom": "ujunox",
                    "amount": "2"
                  }
                ]
              }
            }
          },
          "gas_limit": 62116
        }
      ],
      "rules": null,
      "cw20_coins": []
    }
  }
}
```

### PR DESCRIPTION
**Pull request by deveusss**
closes #221

### CODE REVIEW

File: contracts/cw-croncat/src/manager.rs [hunk 1]
```diff
@@ -349,6 +349,13 @@ impl<'a> CwCroncat<'a> {
             Response::new()
         };
 
+        println!(
+            "{:?} {:?} {:?} {:?}",
```
Comment (TrevorJTClarke) [inline contracts/cw-croncat/src/manager.rs:353]: @deveusss can you remove this?

File: contracts/cw-croncat/src/tasks.rs [hunk 2]
```diff
@@ -414,6 +416,10 @@ impl<'a> CwCroncat<'a> {
             .add_attribute("slot_id", next_id.to_string())
             .add_attribute("slot_kind", format!("{:?}", slot_kind))
             .add_attribute("task_hash", hash)
+            .add_attribute(
```
Comment (TrevorJTClarke) [inline contracts/cw-croncat/src/tasks.rs:419]: I actually dont think we need this one, its nice to have but not necessary as we have the task hash to compute if it is block boundary in an indexer later.

File: contracts/cw-croncat/src/tests/tasks.rs [hunk 3]
```diff
@@ -220,17 +220,17 @@ fn query_get_tasks_pagination() {
...
-        part_of_tasks
-            .iter()
-            .map(|t| t.task_hash.clone())
-            .collect::<Vec<String>>(),
-        all_tasks
-            .iter()
-            .map(|t| t.task_hash.clone())
-            .collect::<Vec<String>>(),
-    );
+    // println!(
```
Comment (TrevorJTClarke) [inline contracts/cw-croncat/src/tests/tasks.rs:223]: if not needed, remove?

**Review by TrevorJTClarke — APPROVED** [review]
Hey @deveusss thanks for the cleanup!!
Just a couple tiny nit picky thangs, then go ahead and merge!!!
